# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yurufuwa-Lab.v2
email: #no-mail-so-far@domain.com
description: > # this means to ignore newlines until "baseurl:"
  もてかわを目指したいアラサーエンジニアのブログ。京都->三鷹の森->インド->横浜。電波系５年生。MOT１年生。
  技術小ネタ、MOT、本、映画、などなど思いついたら書きます。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tsuno788
github_username:  tsuno416

# Build settings
markdown: kramdown
